//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Candidatos = new HashSet<Candidatos>();
            this.Votos = new HashSet<Votos>();
        }
    
        public int usuario_id { get; set; }
        public string usuario_nombres { get; set; }
        public string usuario_apellidos { get; set; }
        public string usuario_documento { get; set; }
        public System.DateTime usuario_fec_nac { get; set; }
        public string usuario_email { get; set; }
        public string usuario_password { get; set; }
        public bool usuario_activo { get; set; }
        public int rol_id { get; set; }
        public int curso_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidatos> Candidatos { get; set; }
        public virtual Cursos Cursos { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Votos> Votos { get; set; }
    }
}
