//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Votos
    {
        public int voto_id { get; set; }
        public int candidato_id { get; set; }
        public int usuario_id { get; set; }
        public System.DateTime fecha_votacion { get; set; }
    
        public virtual Candidatos Candidatos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
